# -*- coding: utf-8 -*-
"""KNNeighborsClassifier_in_Telco-Customer-Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0IJKx5XG2ZPlF7RfrO_96T8Vv_Wz3eX
"""

import numpy as np
import pandas as pd
import seaborn as sns

data=pd.read_csv('/content/drive/MyDrive/WA_Fn-UseC_-Telco-Customer-Churn.csv')

data.head()

data.info()

data.isnull().sum()

from scipy.stats import zscore
z_scores = zscore(data['MonthlyCharges'])
data[np.abs(z_scores)>3]

col=[]
for i in data.columns:
  if data[i].dtype=='object':
    col.append(i)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for i in col:
  data[i] = data[[i]].apply(le.fit_transform)

data

x=data.drop('Churn',axis=1)
y=data['Churn']

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier

kn=KNeighborsClassifier(n_neighbors=150)

kn.fit(xtrain,ytrain)

ypred=kn.predict(xtest)

from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(ytest,ypred)

confusion_matrix(ytest,ypred)